version: "3"

services:

  todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: agranov9/backend-todo:${VERSION}
    ports:
      - "8000:8000"

  todo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: agranov9/frontend-todo:${VERSION}
    ports:
      - "5173:5173"
